require('System\\ScriptCore')
require('System\\ProtocolCore')
require('Scripts\\WelcomeMessage')

require('Scripts\\NpcTalk')
require('Utils\\Database')
require('Utils\\DatabaseAsync')
require('Utils\\Cron')
require('Utils\\Functions')
require('Utils\\Schedule')

--require('Scripts\\MegaSenaEvent\\MegaSena')
--require('Scripts\\MarketPlace\\Init')
--require('Scripts\\SpawnTest\\SpawnTest')
--require('Scripts\\SkinTest')
--require('Scripts\\spaw')
--require('Scripts\\EffectTester')
--require('Scripts\\QuestSystem\\QuestSystemGS')
--requirefolder('Scripts\\TesteProtocol')
--requirefolder('Scripts\\AutoPost')
--requirefolder('Scripts\\QuestSystem')
--requirefolder('Scripts\\ScrambleWords')
--requirefolder('Scripts\\SpotRental')
--requirefolder('Scripts\\MegaSena')
--requirefolder('Scripts\\NpcRescue')
--requirefolder('Scripts\\Recycle')
--requirefolder('Scripts\\TagGame')
--requirefolder('Scripts\\Predador')
--requirefolder('Scripts\\HideAndSeek')
--requirefolder('Scripts\\TreasureHunt')
--requirefolder('Scripts\\DeadorAlive')
--requirefolder('Scripts\\GreenLight')
--requirefolder('Scripts\\HoraBonus')
--requirefolder('Scripts\\HouseOfLuck')
requirefolder('Scripts\\DungeonSystem')

--require("Scripts\\TorreChamas\\TorreChamas_GS_Config")
--require("Scripts\\TorreChamas\\TorreChamas_GS")




DataBase.Connect(3, "MuOnline", "sa", "Gu031988*")
